FROM nvidia/cuda:12.9.0-runtime-ubuntu22.04
SHELL ["/bin/bash", "-c"]

ARG DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y unzip curl openssh-server wget git build-essential cmake aria2 ffmpeg libgl1 python3-venv 
RUN apt-get install -y python3-pip
RUN pip3 install --upgrade pip
RUN pip3 install --no-cache pyyaml
RUN apt-get clean autoclean
RUN apt-get autoremove --yes
RUN echo "Removing apt cache ..."
RUN rm -rf /var/lib/{apt,dpkg,cache,log}/

COPY ./install_comfyui.sh /install_comfyui.sh
RUN chmod +x install_comfyui.sh

ENV USE_SDXL_MODELS="false"
ENV USE_WAN_MODELS="false"
ENV USE_QWEN_MODELS="false"
ENV USE_FLUX_MODELS="false"
ENV USE_HV_MODELS="false"

RUN /install_comfyui.sh
