FROM pablocael/comfyui-base:latest
SHELL ["/bin/bash", "-c"]

USER root
VOLUME /root
WORKDIR /root

COPY models/loras/SDXL/ /root/models/loras/SDXL/
ENV USE_SDXL_MODELS=1

EXPOSE 8188
ENV CLI_ARGS=""
CMD ["bash","/entrypoint.sh"]
